version: '3.8'

services:
  # Backend service
  backend:
    build: ./back
    container_name: breht-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    networks:
      - breht-network

  # Frontend service
  frontend:
    build: ./front
    container_name: breht-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - breht-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: breht-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - breht-network

networks:
  breht-network:
    driver: bridge