networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend


  backend:
    build:
      context: ./back
    networks:
      - dev

  fontend:
    build:
      context: ./front
    networks:
        - dev