version: '3.8'

services:
  backend:
    build: ./back
    container_name: breht-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - breht-network

  frontend:
    build: ./front
    container_name: breht-frontend
    restart: unless-stopped
    networks:
      - breht-network

  nginx:
    image: nginx:alpine
    container_name: breht-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # Добавляем HTTPS порт
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Монтируем SSL сертификаты
    depends_on:
      - frontend
      - backend
    networks:
      - breht-network

networks:
  breht-network:
    driver: bridge